rest-broadcaster:
  fullnameOverride: rest-broadcaster
  nameOverride: rest-broadcaster
  image:
    name: ghcr.io/gattma/restbroadcaster
    tag: sha-5083cca
  route:
    enabled: true
  env:
    - name: HOSTS_LEADER
      value: https://frontend-facade-contest.apps.play.gepaplexx.com
    - name: HOSTS_BROADCASTS
      value: https://frontend-facade-anomaly-response-time-contest.apps.play.gepaplexx.com
