apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rest-broadcaster
spec:
  project: contest
  source:
    repoURL: 'https://github.com/gattma/SolrSearch-CI'
    path: RestBroadcasterChart
    targetRevision: develop
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true