apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-contest-core-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contest-core-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contest-core-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contest-core-role
subjects:
  - kind: ServiceAccount
    name: create-contest-core-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-contest-core
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: create-contest-core-sa
      containers:
        - name: create-contest-core
          image: quay.io/appuio/oc:v4.6
          command: ["/bin/bash", "-c"]
          args:
            - |
              oc wait --for=condition=Ready -l deployment=openshift-solr pods
              oc exec deploy/openshift-solr -- solr create -c contest
      restartPolicy: Never
