apiVersion: v2
name: SolrSearch

type: application

version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: gp-bke-runtime-minimal-application
    version: "0.0.14"
    repository: "https://gepaplexx.github.io/gp-helm-charts/"
    alias: search-service
  - name: gp-bke-runtime-minimal-application
    version: "0.0.14"
    repository: "https://gepaplexx.github.io/gp-helm-charts/"
    alias: frontend-facade

  # TODO apache-solr