search-service:
  fullnameOverride: search-service
  nameOverride: search-service
  image:
    name: ghcr.io/gattma/solrsearchservice-develop
    tag: sha-3b69b97
  # TODO Deployment Annotation not supported by bke-runtime-minimal
  # annotations:
  #    sidecar.jaegertracing.io/inject: "true"
  route:
    enabled: true
  env:
    - name: SOLR_HOSTPORT
      value: solr-contest.apps.play.gepaplexx.com
    - name: SOLR_CORE
      value: contest

frontend-facade:
  fullnameOverride: frontend-facade
  nameOverride: frontend-facade
  image:
    name: ghcr.io/gattma/solrfrontendfacade-develop
    tag: sha-3b69b97
  # TODO Deployment Annotation not supported by bke-runtime-minimal
  # annotations:
  #    sidecar.jaegertracing.io/inject: "true"
  route:
    enabled: true
  env:
    - name: SOLRSEARCHSERVICE_BASEURL
      value: https://search-service-contest.apps.play.gepaplexx.com
